SELECT USER_ID, NICKNAME, CONCAT(CITY," ", STREET_ADDRESS1," ", STREET_ADDRESS2) AS "전체주소", 
CONCAT(LEFT(TLNO,3), "-",SUBSTRING(TLNO,4,4), "-", RIGHT(TLNO, 4)) "전화번호"
FROM USED_GOODS_USER AS U
LEFT JOIN (SELECT WRITER_ID, COUNT(BOARD_ID) AS NUMBER
            FROM USED_GOODS_BOARD 
            GROUP BY WRITER_ID
          ) AS C
ON U.USER_ID = C.WRITER_ID
WHERE C.NUMBER >=3
ORDER BY USER_ID DESC;